const api={register:data=>fetch('/api/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json()),login:data=>fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json()),me:()=>fetch('/api/me').then(r=>r.json()),logout:()=>fetch('/api/logout',{method:'POST'}).then(r=>r.json()),users:()=>fetch('/api/users').then(r=>r.json()),deleteUser:id=>fetch('/api/users/delete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id})}).then(r=>r.json()),toggleAdmin:(id,makeAdmin)=>fetch('/api/users/toggle-admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,makeAdmin})}).then(r=>r.json()),ban:id=>fetch('/api/users/ban',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id})}).then(r=>r.json()),unban:id=>fetch('/api/users/unban',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id})}).then(r=>r.json())};


const main=document.getElementById('main');
const authBtn=document.getElementById('authBtn');
const authModal=document.getElementById('authModal');
const authTitle=document.getElementById('authTitle');
const nameInput=document.getElementById('nameInput');
const emailInput=document.getElementById('emailInput');
const passwordInput=document.getElementById('passwordInput');
const submitAuth=document.getElementById('submitAuth');
const closeAuth=document.getElementById('closeAuth');
const switchToSignup=document.getElementById('switchToSignup');
const authError=document.getElementById('authError');
const userArea=document.getElementById('userArea');
let mode='login';
function showModal(m='login'){mode=m;authModal.classList.remove('hidden');authError.textContent='';if(m==='login'){authTitle.textContent='Sign In';nameInput.classList.add('hidden');}else{authTitle.textContent='Create account';nameInput.classList.remove('hidden');}}
function hideModal(){authModal.classList.add('hidden');}
authBtn.addEventListener('click',()=>showModal('login'));
switchToSignup.addEventListener('click',()=>showModal('signup'));
closeAuth.addEventListener('click',hideModal);
submitAuth.addEventListener('click',async()=>{const email=emailInput.value.trim();const password=passwordInput.value.trim();const name=nameInput.value.trim();authError.textContent='';try{let res;if(mode==='login'){res=await api.login({email,password});if(res.error){if(res.error==='BANNED'&&res.redirect)return window.location.href=res.redirect;throw new Error(res.error);}}else{res=await api.register({email,password,name});if(res.error)throw new Error(res.error);}hideModal();await refreshUser();navigate(window.location.pathname||'/');}catch(e){authError.textContent=e.message}});
async function refreshUser(){const r=await api.me();if(r&&r.user){userArea.innerHTML=`<span>${r.user.name}</span> <button id="logoutBtn">Logout</button>`;document.getElementById('logoutBtn').addEventListener('click',async()=>{await api.logout();await refreshUser();navigate('/');});}else{userArea.innerHTML='';}}
const tabs=document.querySelectorAll('.tabs a');for(const t of tabs){t.addEventListener('click',(e)=>{e.preventDefault();navigate(t.getAttribute('data-route'))})}
async function navigate(route){const publicRoutes=['/','/login','/signup'];const r=await api.me();const authed=r&&r.user;if(!authed&&!publicRoutes.includes(route)){showModal('login');return;}if(route==='/'){main.innerHTML=`<div class="page"><h1>Welcome to Anton</h1><div class="card"><p>Futuristic browser UI</p></div></div>`;}else if(route==='/browser'){main.innerHTML=`<div class="page"><h2>Browser</h2><div class="card"><iframe src="https://example.com" style="width:100%;height:60vh;border-radius:12px;border:none"></iframe></div></div>`;}else if(route==='/ai'){main.innerHTML=`<div class="page"><h2>AI</h2><div class="card">AI features</div></div>`;}else if(route==='/vm'){main.innerHTML=`<div class="page"><h2>VM</h2><div class="card">VM control</div></div>`;}else if(route==='/youtube'){main.innerHTML=`<div class="page"><h2>YouTube</h2><div class="card">YouTube area</div></div>`;}else if(route==='/support'){main.innerHTML=`<div class="page"><h2>Support</h2><div class="card">Support center</div></div>`;}else if(route==='/admin'){const usersRes=await api.users();if(usersRes.error)return showModal('login');const users=usersRes.users||[];main.innerHTML=`<div class="page"><h2>Admin Panel</h2><table class="table"><thead><tr><th>Email</th><th>Name</th><th>Admin</th><th>Banned</th><th>Actions</th></tr></thead><tbody id="usersTbody"></tbody></table></div>`;const tbody=document.getElementById('usersTbody');tbody.innerHTML=users.map(u=>`<tr><td>${u.email}</td><td>${u.name}</td><td>${u.isAdmin?'Yes':'No'}</td><td>${u.banned?'Yes':'No'}</td><td><button class="small" data-act="toggle" data-id="${u.id}">Toggle Admin</button> <button class="small" data-act="ban" data-id="${u.id}">${u.banned?'Unban':'Ban'}</button> <button class="small" data-act="del" data-id="${u.id}">Delete</button></td></tr>`).join('');tbody.querySelectorAll('button').forEach(b=>b.addEventListener('click',async()=>{const id=b.getAttribute('data-id');const act=b.getAttribute('data-act');if(act==='toggle'){await api.toggleAdmin(id,true);await navigate('/admin');}if(act==='ban'){if(confirm('Toggle ban?')){await api.ban(id);await navigate('/admin');}}if(act==='del'){if(confirm('Delete user?')){await api.deleteUser(id);await navigate('/admin');}}}))}}
refreshUser();navigate('/');
